import { NextResponse } from "next/server";
import { auth } from "@/auth";
import connectDB from "@/lib/db";
import BusinessHealthSummary from "@/models/admin/BusinessHealthSummary";

/**
 * Latest AI business-health summary for the current tenant (Phase 4).
 * Generated by the scheduled cron (app/api/cron/business-health) — this
 * just reads the most recent one for display on the admin dashboard.
 */
export async function GET() {
  const session = await auth();
  const tenantId = (session?.user as any)?.tenantId as string | undefined;
  if (!tenantId) return NextResponse.json({ success: false }, { status: 401 });

  await connectDB();
  const summary = await BusinessHealthSummary.findOne({ tenantId }).sort({ generatedAt: -1 }).lean();

  return NextResponse.json({ success: true, data: summary });
}
