// Resident withholding defaults, effective 1 April 2026. Thresholds, PAN,
// certificates and special/non-resident rates require taxpayer-specific review.
// Source: Income-tax Act 2025 as amended by Finance Act 2026, ss. 393–394.
// Legacy references are search aids, not current return-filing section codes.
export const TDS_RATES = [
  ["192A", "Taxable provident fund withdrawal", 10],
  ["193", "Interest on securities", 10],
  ["194", "Dividends", 10],
  ["194A", "Interest other than securities", 10],
  ["194B", "Lottery / gambling winnings", 30],
  ["194BA", "Online game winnings", 30],
  ["194BB", "Horse race winnings", 30],
  ["194C", "Contractor - individual/HUF", 1],
  ["194C", "Contractor - others", 2],
  ["194D", "Insurance commission - non-company", 5],
  ["194D", "Insurance commission - company", 10],
  ["194DA", "Life insurance income", 2],
  ["194EE", "National Savings Scheme", 10],
  ["194G", "Lottery ticket commission", 2],
  ["194H", "Commission / brokerage", 2],
  ["194I", "Rent - plant / machinery", 2],
  ["194I", "Rent - land / building", 10],
  ["194IA", "Immovable property", 1],
  ["194IB", "Rent by individual / HUF", 2],
  ["194IC", "Joint development consideration", 10],
  ["194J", "Technical services / call centre / film royalty", 2],
  ["194J", "Professional fees / other royalty", 10],
  ["194K", "Unit income", 10],
  ["194LA", "Compulsory acquisition compensation", 10],
  ["194LBA", "Business trust - resident", 10],
  ["194LBB", "Investment fund - resident", 10],
  ["194LBC", "Securitisation trust - resident", 10],
  ["194M", "Individual / HUF contractual payments", 2],
  ["194N", "Cash withdrawals - standard", 2],
  ["194N", "Cash withdrawals - higher band", 5],
  ["194O", "E-commerce participant", 0.1],
  ["194Q", "Purchase of goods", 0.1],
  ["194R", "Business benefits / perquisites", 10],
  ["194S", "Virtual digital assets", 1],
  ["194T", "Payments to partners", 10],
].map(([legacy, description, rate]) => ({ label: `${description} (${rate}%; legacy ${legacy})`, rate: Number(rate), sectionCode: "393(1)" }));
export const TCS_RATES = [
  ["1", "Alcoholic liquor", 2], ["2", "Tendu leaves", 2],
  ["3", "Timber / forest produce", 2], ["4", "Scrap", 2],
  ["5", "Coal / lignite / iron ore", 2],
  ["6", "Motor vehicles / notified goods above threshold", 1],
  ["7", "LRS education / medical - taxable excess", 2],
  ["7", "LRS other purposes - taxable excess", 20],
  ["8", "Overseas tour package", 2],
  ["9", "Parking / toll / mining / quarry lease", 2],
].map(([row, description, rate]) => ({ label: `${description} (${rate}%)`, rate: Number(rate), sectionCode: `394(1) Table ${row}` }));
