import dbConnect from "@/lib/db";
import CrmAutomationRule from "@/models/crm/AutomationRule";
import CrmAutomationExecution from "@/models/crm/AutomationExecution";
import CrmTask from "@/models/crm/Task";
import CrmActivity from "@/models/crm/Activity";
import CrmCommunication from "@/models/crm/Communication";
import CrmContract from "@/models/crm/Contract";
import CrmAuditLog from "@/models/crm/CrmAuditLog";
import mongoose from "mongoose";

/**
 * Triggers an automation check for a specific event and record.
 * @param tenantId The tenant ID
 * @param trigger The trigger name (e.g., "record_created", "stage_changed", "quote_accepted")
 * @param entity The entity type (e.g., "Lead", "Opportunity")
 * @param entityId The ID of the record
 * @param payload The current state of the record or event payload
 */
export async function triggerAutomation(
  tenantId: string,
  trigger: string,
  entity: string,
  entityId: string,
  payload: any
) {
  await dbConnect();

  // Find enabled rules matching this trigger and entity
  const rules = await CrmAutomationRule.find({
    tenantId,
    trigger,
    entity,
    enabled: true,
  });

  for (const rule of rules) {
    if (evaluateConditions(rule.conditions, payload)) {
      await executeRule(rule, entity, entityId, payload);
    }
  }
}

/**
 * Evaluates a set of conditions against a payload.
 */
function evaluateConditions(conditions: any[], payload: any): boolean {
  if (!conditions || conditions.length === 0) return true;

  return conditions.every((cond) => {
    const fieldValue = payload[cond.field];
    switch (cond.operator) {
      case "equals": return fieldValue === cond.value;
      case "not_equals": return fieldValue !== cond.value;
      case "contains": return String(fieldValue).includes(String(cond.value));
      case "greater_than": return fieldValue > cond.value;
      case "less_than": return fieldValue < cond.value;
      case "exists": return cond.value ? (fieldValue !== undefined && fieldValue !== null) : (fieldValue === undefined || fieldValue === null);
      // Date ops could be more complex, simplifying for now
      default: return false;
    }
  });
}

/**
 * Executes the actions defined in a rule.
 */
async function executeRule(rule: any, entity: string, entityId: string, payload: any) {
  const execution = await CrmAutomationExecution.create({
    tenantId: rule.tenantId,
    ruleId: rule._id,
    trigger: rule.trigger,
    entity,
    entityId,
    status: "Running",
  });

  try {
    for (const action of rule.actions) {
      switch (action.type) {
        case "create_task":
          await CrmTask.create({
            tenantId: rule.tenantId,
            title: action.payload.title || `Task generated by ${rule.name}`,
            related_record_type: entity,
            related_record_id: entityId,
            due_date: new Date(Date.now() + 86400000), // Next day
            owner_id: payload.owner_id || rule.createdBy,
            priority: "High",
            createdBy: rule.createdBy
          });
          break;
        case "create_activity":
          await CrmActivity.create({
            tenantId: rule.tenantId,
            activity_type: "System",
            record_type: entity,
            record_id: entityId,
            subject: action.payload.subject || `Activity generated by ${rule.name}`,
            status: "Completed",
            owner_id: payload.owner_id || rule.createdBy,
            createdBy: rule.createdBy
          });
          break;
        case "send_email":
        case "send_whatsapp":
        case "send_sms":
          await CrmCommunication.create({
            tenantId: rule.tenantId,
            recordType: entity,
            recordId: entityId,
            channel: action.type === "send_email" ? "Email" : action.type === "send_whatsapp" ? "WhatsApp" : "SMS",
            direction: "outbound",
            message: action.payload.message || `Automated message from ${rule.name}`,
            sender: "system@aupulens.com",
            recipient: payload.email || payload.phone || "unknown",
            status: "Sent",
            sentAt: new Date(),
            createdBy: rule.createdBy
          });
          break;
        case "change_status":
        case "update_field":
          // Dynamic model import based on entity
          const map: Record<string, string> = { "Lead": "CrmLead", "Opportunity": "CrmOpportunity", "Quote": "CrmQuote", "Case": "CrmCase", "Contract": "CrmContract" };
          const modelName = map[entity] || `Crm${entity}`;
          const Model = mongoose.models[modelName];
          if (Model) {
            await Model.updateOne({ _id: entityId }, { $set: action.payload });
          }
          break;
        case "create_related_record":
          if (action.payload.target === "Contract" && entity === "Quote") {
            // Rule 10: Quote Accepted Workflow
            const contract = await CrmContract.create({
              tenantId: rule.tenantId,
              contract_number: `CTR-${Date.now().toString(36).toUpperCase()}`,
              account_id: payload.account_id,
              quote_id: entityId,
              owner_id: payload.owner_id || rule.createdBy,
              status: "Active",
              start_date: new Date(),
              end_date: new Date(Date.now() + 31536000000), // +1 year
              contract_value: payload.grand_total || 0,
              billing_frequency: "Annual",
              createdBy: rule.createdBy
            });
            await CrmAuditLog.create({
              tenantId: rule.tenantId,
              user_id: rule.createdBy,
              action: "created",
              record_type: "Contract",
              record_id: contract._id,
              new_value: "Auto-generated from accepted Quote",
              timestamp: new Date()
            });
          }
          break;
      }
    }

    execution.status = "Completed";
    execution.completedAt = new Date();
    await execution.save();
    
    await CrmAutomationRule.updateOne(
      { _id: rule._id },
      { $inc: { executionCount: 1 }, $set: { lastExecutedAt: new Date() } }
    );
  } catch (error: any) {
    execution.status = "Failed";
    execution.error = error.message;
    await execution.save();
  }
}
