import { INVOICE_TEMPLATE_KEY } from "@/lib/constants/statuses";
import type { TemplateDefinition } from "./types";

// 14 ORIGINAL invoice template layouts. Names only describe structural style
// (see docs/_context/ERP.md Sales section) — no third-party brand is
// referenced or reproduced anywhere in these definitions or their renderer.
//
// Only 9 are ACTIVE (appear in the gallery/selector/seeds) per the current
// scope; the other 5 are kept dormant (active:false) rather than deleted so
// they can be re-activated later without rebuilding them from scratch.
export const TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  {
    key: INVOICE_TEMPLATE_KEY.MODERN,
    name: "Modern",
    category: "invoice",
    description: "Clean minimal header, three-block customer/meta row, generous whitespace.",
    active: true,
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "none",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#276EF1",
  },
  {
    key: INVOICE_TEMPLATE_KEY.VINTAGE,
    name: "Vintage",
    category: "invoice",
    description: "Bordered full-grid tax-invoice table with a serif, ornate double-rule header.",
    active: false,
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "bordered-grid",
    borderStyle: "double",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#8B5E34",
  },
  {
    key: INVOICE_TEMPLATE_KEY.MRP_DISCOUNT,
    name: "MRP + Discount",
    category: "invoice",
    description: "Retail layout: MRP + Selling Price columns, per-line discount from MRP, Amount Payable/Paid block.",
    active: true,
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: true,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: true,
    accentColorDefault: "#DC2626",
  },
  {
    key: INVOICE_TEMPLATE_KEY.ELEGANT,
    name: "Elegant",
    category: "invoice",
    description: "Refined serif type, centered header, thin gold-toned rules.",
    active: false,
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "centered",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#9333EA",
  },
  {
    key: INVOICE_TEMPLATE_KEY.SERVICE,
    name: "Service",
    category: "invoice",
    description: "Service-line layout (Description / HSN-SAC / Amount), prominent Bill To / Ship To, no goods-heavy columns.",
    active: true,
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: true,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#0EA5E9",
  },
  {
    key: INVOICE_TEMPLATE_KEY.LANDSCAPE,
    name: "Landscape",
    category: "invoice",
    description: "Landscape A4 orientation — wide top band and wide items table using the extra width.",
    active: true,
    orientation: "landscape",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: true,
    retailTotals: false,
    accentColorDefault: "#2563EB",
  },
  {
    key: INVOICE_TEMPLATE_KEY.EVERGREEN,
    name: "Evergreen",
    category: "invoice",
    description: "Light bordered layout, seller top-left with logo, boxed customer block, airy and professional.",
    active: true,
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: true,
    retailTotals: false,
    accentColorDefault: "#16A34A",
  },
  {
    key: INVOICE_TEMPLATE_KEY.ELEGANT_IMAGES,
    name: "Elegant with Images",
    category: "invoice",
    description: "Elegant layout extended with a product-thumbnail column in the items table.",
    active: false,
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "centered",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: true,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#9333EA",
  },
  {
    key: INVOICE_TEMPLATE_KEY.CLASSIC,
    name: "Classic",
    category: "invoice",
    description: "Traditional bordered full-grid tax-invoice table, boxed seller + customer header, HSN summary grid.",
    active: true,
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "bordered-grid",
    borderStyle: "heavy-grid",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: true,
    retailTotals: false,
    accentColorDefault: "#1F2937",
  },
  {
    key: INVOICE_TEMPLATE_KEY.COMPACT,
    name: "Compact",
    category: "invoice",
    description: "Dense single-page layout with condensed rows — ideal for many line items.",
    active: true,
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "compact",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#0284C7",
  },
  {
    key: INVOICE_TEMPLATE_KEY.BILL_SHIP,
    name: "Bill To - Ship To",
    category: "invoice",
    description: "Prominent Bill From/Ship From + Bill To/Ship To four-block header for logistics/shipping context.",
    active: true,
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "dual-address",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: true,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#4F46E5",
  },
  {
    key: INVOICE_TEMPLATE_KEY.LEGEND,
    name: "Legend",
    category: "invoice",
    description: "Full-bordered detailed grid — the most 'official document' look, complete HSN summary, bordered bottom band.",
    active: true,
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "bordered-grid",
    borderStyle: "heavy-grid",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: true,
    retailTotals: false,
    accentColorDefault: "#BE123C",
  },
  {
    key: INVOICE_TEMPLATE_KEY.SERVICE_2,
    name: "Service 2",
    category: "invoice",
    description: "Alternate service layout — horizontal-rule separated, description-heavy rows.",
    active: false,
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "minimal",
    borderStyle: "none",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: true,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#D97706",
  },
  {
    key: INVOICE_TEMPLATE_KEY.GENZ,
    name: "genZ",
    category: "invoice",
    description: "Bold colored gradient header band with a big total callout.",
    active: false,
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "gradient-band",
    borderStyle: "none",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    hsnSummaryEmphasis: false,
    retailTotals: false,
    accentColorDefault: "#7C3AED",
  },
];

/** The 9 categories currently in scope — the only ones surfaced in the gallery/selector/seeds. */
export const ACTIVE_TEMPLATE_DEFINITIONS: TemplateDefinition[] = TEMPLATE_DEFINITIONS.filter((t) => t.active);
export const ACTIVE_TEMPLATE_KEYS: string[] = ACTIVE_TEMPLATE_DEFINITIONS.map((t) => t.key);

export function getTemplateDefinition(key: string): TemplateDefinition {
  return TEMPLATE_DEFINITIONS.find((t) => t.key === key) || TEMPLATE_DEFINITIONS[0];
}
