import { INVOICE_TEMPLATE_KEY } from "@/lib/constants/statuses";
import type { TemplateDefinition } from "./types";

// 14 ORIGINAL invoice template layouts. Names only describe structural style
// (see docs/_context/ERP.md Sales section) — no third-party brand is
// referenced or reproduced anywhere in these definitions or their renderer.
export const TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  {
    key: INVOICE_TEMPLATE_KEY.MODERN,
    name: "Modern",
    category: "invoice",
    description: "Clean minimal header, generous whitespace, single accent rule.",
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "none",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#276EF1",
  },
  {
    key: INVOICE_TEMPLATE_KEY.VINTAGE,
    name: "Vintage",
    category: "invoice",
    description: "Bordered full-grid tax-invoice table with a serif, ornate double-rule header.",
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "bordered-grid",
    borderStyle: "double",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#8B5E34",
  },
  {
    key: INVOICE_TEMPLATE_KEY.MRP_DISCOUNT,
    name: "MRP + Discount",
    category: "invoice",
    description: "Retail-style layout with an explicit MRP column alongside selling price and discount.",
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: true,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#DC2626",
  },
  {
    key: INVOICE_TEMPLATE_KEY.ELEGANT,
    name: "Elegant",
    category: "invoice",
    description: "Refined serif type, centered header, thin gold-toned rules.",
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "centered",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#9333EA",
  },
  {
    key: INVOICE_TEMPLATE_KEY.SERVICE,
    name: "Service",
    category: "invoice",
    description: "Service-line layout without HSN-heavy goods columns — description-first rows.",
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: true,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#0EA5E9",
  },
  {
    key: INVOICE_TEMPLATE_KEY.LANDSCAPE,
    name: "Landscape",
    category: "invoice",
    description: "Landscape A4 orientation with a wide items table.",
    orientation: "landscape",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#2563EB",
  },
  {
    key: INVOICE_TEMPLATE_KEY.EVERGREEN,
    name: "Evergreen",
    category: "invoice",
    description: "Green-accented layout with a leaf-style side rule and rounded cards.",
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#16A34A",
  },
  {
    key: INVOICE_TEMPLATE_KEY.ELEGANT_IMAGES,
    name: "Elegant with Images",
    category: "invoice",
    description: "Elegant layout extended with a product-thumbnail column in the items table.",
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "centered",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: true,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#9333EA",
  },
  {
    key: INVOICE_TEMPLATE_KEY.CLASSIC,
    name: "Classic",
    category: "invoice",
    description: "Traditional bordered full-grid tax-invoice table, corporate black & white.",
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "bordered-grid",
    borderStyle: "heavy-grid",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#1F2937",
  },
  {
    key: INVOICE_TEMPLATE_KEY.COMPACT,
    name: "Compact",
    category: "invoice",
    description: "Dense single-page layout with condensed rows — ideal for many line items.",
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "minimal",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "compact",
    billShipProminent: false,
    accentColorDefault: "#0284C7",
  },
  {
    key: INVOICE_TEMPLATE_KEY.BILL_SHIP,
    name: "Bill To - Ship To",
    category: "invoice",
    description: "Prominent dual address block giving Bill To and Ship To equal visual weight.",
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "dual-address",
    borderStyle: "thin",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: true,
    accentColorDefault: "#4F46E5",
  },
  {
    key: INVOICE_TEMPLATE_KEY.LEGEND,
    name: "Legend",
    category: "invoice",
    description: "Sidebar layout — a colored summary column runs alongside the main items list.",
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "sidebar",
    borderStyle: "none",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#BE123C",
  },
  {
    key: INVOICE_TEMPLATE_KEY.SERVICE_2,
    name: "Service 2",
    category: "invoice",
    description: "Alternate service layout — horizontal-rule separated, description-heavy rows.",
    orientation: "portrait",
    fontFamily: "serif",
    headerStyle: "minimal",
    borderStyle: "none",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: true,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#D97706",
  },
  {
    key: INVOICE_TEMPLATE_KEY.GENZ,
    name: "genZ",
    category: "invoice",
    description: "Bold colored gradient header band with a big total callout.",
    orientation: "portrait",
    fontFamily: "sans",
    headerStyle: "gradient-band",
    borderStyle: "none",
    showMrpColumn: false,
    showImages: false,
    serviceStyle: false,
    density: "normal",
    billShipProminent: false,
    accentColorDefault: "#7C3AED",
  },
];

export function getTemplateDefinition(key: string): TemplateDefinition {
  return TEMPLATE_DEFINITIONS.find((t) => t.key === key) || TEMPLATE_DEFINITIONS[0];
}
